app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.bfwg: DEBUG

server:
  address: 192.168.1.13
  port: 8080

spring:
#  mail:
#    host: 192.168.1.10
#    port: 25
#    username: webapps
#    password: W3b@pps
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            #ssl:
#              #enable: true
#          auth: true
#          ehlo: false
#          debug: true
#          host: 192.168.1.10
#          protocol: smtps
          #ssl:
            #enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      #ddl-auto: update
       ddl-auto: create
    show-sql: true

#mail:
#  smpt:
#  host: 192.168.1.10
#  port: 25
#  username: webapps
#  password: W3b@pps
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#              #ssl:
#            #enable: true
#          auth: true
#          ehlo: false
#          debug: true
#          host: 192.168.1.10
#          protocol: smtps
            #ssl:
          #enabled: true
